### PR TITLE
Db list incidents & manager incident report

### PR DESCRIPTION
**Pull request by HubDub**
## Pull Request Description

created action to list employees incidents and action to show manager incident report.

## Steps to Test

1. git fetch
1. git checkout db-ListIncidents
1. make sure all tests run successfully
1. log in, make sure you can list your incidents. Make sure admin can log in and view incident report

## Link to Feature Ticket

#29 
#4

### CODE REVIEW

**Comment by Jgregnier** [comment]
:south_georgia_south_sandwich_islands:

**Review by thrashMoneyVillainare — COMMENTED** [review]
:south_georgia_south_sandwich_islands:

**Review by delaineackerman — COMMENTED** [review]
Works on my machine

**Review by csmalley89 — COMMENTED** [review]
LGTM

**Review by JamsDuke — COMMENTED** [review]
Might want to reduce the amount of decimal places we are showing.  Otherwise, LGTM 🍖

**Review by JamsDuke — APPROVED** [review]

**Pull request merged**
