### PR TITLE
Added thorough documentation to all files assigned to me

### PR DESCRIPTION
**Pull request by Jgregnier**
## Pull Request Description

1. Documented all Classes and methods assigned to me. 

## Steps to Test

1. Check for spelling errors and see that documentation is sufficient.

## Link to Feature Ticket

#56, #62 , #68

### CODE REVIEW

**Review by JamsDuke — COMMENTED** [review]
:feelsgood:

**Review by csmalley89 — COMMENTED** [review]
🎱

**Review by delaineackerman — COMMENTED** [review]
LGTM

**Comment by HubDub** [comment]
employeefactory.cs line 12 has an extra ")" at the end. other than that, perfect.

**Review by thrashMoneyVillainare — COMMENTED** [review]
looks good minus the extra ')'

**Review by delaineackerman — APPROVED** [review]

**Pull request merged**
