### PR TITLE
Added documentation and removed unnecessary using statements

### PR DESCRIPTION
**Pull request by csmalley89**
## Pull Request Description

Added documentation to Order.cs, CustomerIncidentConnection.cs, and IncidentReport.cs. As well as removed unnecessary using statements.

## Steps to Test

1. Look over comments added to the files. 
1. Adjust/Comment on any changes needed.
1. Have a nice day.

### CODE REVIEW

**Review by Jgregnier — COMMENTED** [review]
Class or Method documentation should be right before the class or method is being used. Not below it. Customer Incident Connection is misnamed as incident report. Content looks good though.

**Review by delaineackerman — COMMENTED** [review]
LGTM

**Comment by HubDub** [comment]
agree with Grant. CustomerIncidentConnection.cs documentation needs to be moved above the class and the method. other than that, looks great!

**Review by JamsDuke — COMMENTED** [review]
LGTM

**Review by thrashMoneyVillainare — COMMENTED** [review]
what Grant said about the CustomerIncidentConnection class aside looks good.

**Review by JamsDuke — APPROVED** [review]

**Pull request merged**
