### PR TITLE
Added issues and pull request templates

### PR DESCRIPTION
**Pull request by delaineackerman**
* Added a .github folder
  * Created an issues template
  * Created a pull request template

Issue #7

### CODE REVIEW

**Review by JamsDuke — COMMENTED** [review]
looks good

**Review by thrashMoneyVillainare — COMMENTED** [review]
yes

**Review by Jgregnier — COMMENTED** [review]
🍊

**Review by csmalley89 — COMMENTED** [review]
👍

**Review by HubDub — APPROVED** [review]
looks good

**Pull request merged**
