### PR TITLE
documentation for IncidentDetail.cs, NewUser.cs, Employee.cs, Program.cs

### PR DESCRIPTION
**Pull request by HubDub**
## Pull Request Description

Include the applicable information from the list below here 

1. Added documentation for IncidentDetail.cs, NewUser.cs, Employee.cs, Program.cs

## Steps to Test

1. review files for any errors

## Link to Feature Ticket

#71 
#63 
#58 
#54

### CODE REVIEW

**Review by csmalley89 — COMMENTED** [review]
👍

**Comment by Jgregnier** [comment]
Looks good other than the documentation below the classes/ methods instead of above it.

**Review by delaineackerman — COMMENTED** [review]
LGTM

**Review by JamsDuke — COMMENTED** [review]
LGTM

**Review by thrashMoneyVillainare — APPROVED** [review]
🍏

**Pull request merged**
