### PR TITLE
sql tables and seed data

### PR DESCRIPTION
**Pull request by HubDub**
this .sql file creates the four tables according to the ERD and then seeded some data.
  Employees - seeded six employees
  Incidents - no seeded data
  Departments - seeded departments
  IncidentTypes - seeded incident types

to check this branch:
git fetch 
git checkout db-seeds
in root folder touch a database file (for ex. "CustomerIncidentDatabase.db")
sqlite3 CustomerIncidentDataBase.db < PopulateSQL.sql 
    *whatever you name your db file must be the name you put after the sqlite3 above*
go into DB browser for SQLite, open the database you just created, and verify the tables and data are in there.

### CODE REVIEW

**Review by thrashMoneyVillainare — COMMENTED** [review]
even though im not an admin, lgtm

**Review by Jgregnier — COMMENTED** [review]
🍓 
🍒

**Review by JamsDuke — COMMENTED** [review]
Code pulled, tested, verified.

**Review by delaineackerman — APPROVED** [review]
LGTM

**Pull request merged**
