### PR TITLE
Completed NewUser and MainMenu actions, tests for if departments exist.

### PR DESCRIPTION
**Pull request by thrashMoneyVillainare**
## Pull Request Description

In this PR, there are actions for New Users, and the the Main Menu.
There is a new Department entity and factory.
There is a new Department test, testing that a table on the DB named Departments exists and that it will return data, 

1. Fetch and pull down zr-newUser
1. Run Department test and make sure it passes.
1. Run the program and find bugs/try to break the app. 
1. Have fun.

## Steps to Test

Include the applicable information from the list below here

1. System configuration.
2. 3rd party libraries that need to be installed (if applicable).
3. Command line utilities to run.
4. If there is a UI component, give clear instructions for steps to perform in the UI, and what they should expect to see as the outcome of those steps.

## Link to Feature Ticket

Provide the issue number that this pull request fixes
Example: #1

### CODE REVIEW

**Review by Jgregnier — COMMENTED** [review]
🍇

**Comment by HubDub** [comment]
this works on my machine

**Review by delaineackerman — COMMENTED** [review]
LGTM

**Review by csmalley89 — COMMENTED** [review]
LGTM

**Review by JamsDuke — COMMENTED** [review]
Pulled and tested, works as intended.

**Review by JamsDuke — APPROVED** [review]

**Pull request merged**
