### PR TITLE
Db testing intro

### PR DESCRIPTION
**Pull request by HubDub**
## Pull Request Description

1. created two tests to create a new employee.
.1 then created code to make these tests pass. 

## Steps to Test

Include the applicable information from the list below here

1. git fetch
2. git checkout db-testingIntro
3. build the solution
4. run the tests. They should both pass. 

## Link to Feature Ticket

Provide the issue number that this pull request fixes
Example: #35

### CODE REVIEW

**Review by Jgregnier — COMMENTED** [review]
Needs to be merging into Dev instead of Master. 

Also the CustomerIncidentConnection.Cs Should be getting the connection from an env variable. I cant remember what we agreed upon for the "New" DB Variable name.

**Review by thrashMoneyVillainare — COMMENTED** [review]
Needs to merge with the 'dev' branch

**Review by delaineackerman — COMMENTED** [review]
LGTM

**Review by JamsDuke — COMMENTED** [review]
LGTM

**Review by Jgregnier — COMMENTED** [review]
🌻

**Review by thrashMoneyVillainare — APPROVED** [review]
okieDokie

**Pull request merged**
