### PR TITLE
wrote tests and implemented code for saving incidents, listing incide…

### LINKED ISSUE #31: Customer Factory
## Feature Description

It will hold the active customer and allow the user to get information on all other customers.
 
### Steps for Implementation

1. Create a singleton instance of the customer factory.
1. Query the old database for the customer information by first and last name.

### PR DESCRIPTION
**Pull request by JamsDuke**
## Pull Request Description

Include the applicable information from the list below here 

1. Tested whether or not incidents can be saved to the database.
1. Incidents can be created with customer first and last name.
1. Tested that an incident could be created.

## Steps to Test

Include the applicable information from the list below here

1. Git fetch
1. Switch to branch jd-incidentTest
1. Make sure all tests pass (restart VS if any fail)

## Link to Feature Ticket

Provide the issue number that this pull request fixes
#31, #32, #3

### CODE REVIEW

**Review by Jgregnier — COMMENTED** [review]
🐻

**Comment by HubDub** [comment]
looks great!

**Review by thrashMoneyVillainare — COMMENTED** [review]
🍇

**Review by delaineackerman — COMMENTED** [review]
Works on my machine

**Review by csmalley89 — COMMENTED** [review]
👍

**Review by Jgregnier — APPROVED** [review]

**Pull request merged**
