### PR TITLE
cleared console when IncidentDetail.Action runs

### PR DESCRIPTION
**Pull request by thrashMoneyVillainare**
## Pull Request Description

Console clears on incident detail view/action.

## Steps to Test

pull down zr-ClearConsoleOnIncidentDetail 
run program.
get to incident detail
behold

### CODE REVIEW

**Comment by Jgregnier** [comment]
⚔

**Review by JamsDuke — COMMENTED** [review]
🗡

**Comment by HubDub** [comment]
this works on mine

**Review by delaineackerman — COMMENTED** [review]
LGTM

**Review by csmalley89 — COMMENTED** [review]
👍

**Review by HubDub — APPROVED** [review]

**Pull request merged**
