### PR TITLE
Added documentation to two classes as a team

### PR DESCRIPTION
**Pull request by delaineackerman**
## Pull Request Description

Include the applicable information from the list below here 

Look over the documentation and make sure there are no typos or unclear statements.

### CODE REVIEW

**Review by csmalley89 — COMMENTED** [review]
👍

**Comment by HubDub** [comment]
this looks good to me

**Review by JamsDuke — COMMENTED** [review]
🍤

**Review by Jgregnier — COMMENTED** [review]
🏉

**Review by thrashMoneyVillainare — APPROVED** [review]
:south_georgia_south_sandwich_islands:

**Pull request merged**
