### PR TITLE
added documentation for assigned files

### PR DESCRIPTION
**Pull request by JamsDuke**
## Pull Request Description

Include the applicable information from the list below here 

1. wrote in comments for the files I was assigned.

## Steps to Test

Include the applicable information from the list below here

1. git fetch
1. switch to branch jd-commentCode
1. look over comments added to BangazonWebConnection.cs, DepartmentTest.cs, Banner.cs, and IncidentType.cs 

## Link to Feature Ticket

Provide the issue number that this pull request fixes
Example: #51, #59, #65, #72

### CODE REVIEW

**Comment by Jgregnier** [comment]
LGTM

**Review by delaineackerman — COMMENTED** [review]
LGTM

**Comment by HubDub** [comment]
looks good

**Review by thrashMoneyVillainare — APPROVED** [review]
💛

**Pull request merged**
