### PR TITLE
Ddw create incident

### PR DESCRIPTION
**Pull request by delaineackerman**
## Pull Request Description
 
Allows an employee to create an incident by filling out three prompts

## Steps to Test

Include the applicable information from the list below here

1. `git fetch`
1. `git checkout ddw-create-incident`
1. Make sure you can create an incident that saves to your database
1. Make sure all tests pass

## Link to Feature Ticket

#46

### CODE REVIEW

**Comment by Jgregnier** [comment]
Line 44 of CreateIncident.Cs doesn't need to console.write the customerId. other than that looks 🍑  to me

**Comment by HubDub** [comment]
this works on my machine

**Review by csmalley89 — COMMENTED** [review]
👍

**Review by thrashMoneyVillainare — COMMENTED** [review]
🌽

**Review by JamsDuke — APPROVED** [review]
LGTM

**Pull request merged**
