### PR TITLE
Added connection to old DB

### PR DESCRIPTION
**Pull request by Jgregnier**
## Pull Request Description
I added a new DB connection to our Data directory. 
Resolved a lot of reference issues with Steve. 

Look at the new DB Connection file and check for issues.

### CODE REVIEW

**Review by JamsDuke — COMMENTED** [review]
Looks good

**Review by thrashMoneyVillainare — COMMENTED** [review]
yes

**Comment by HubDub** [comment]
good

**Review by delaineackerman — COMMENTED** [review]
Works on my machine

**Review by delaineackerman — APPROVED** [review]

**Pull request merged**
