### PR TITLE
Cs incident details

### PR DESCRIPTION
**Pull request by csmalley89**
## Pull Request Description

1. Created Incident Details Page
1. Created Tests for the detail page.
1. Update PopulateSQL.sql

## Steps to Test

1. Git Fetch
1. Git Checkout cs-IncidentDetails
1. Delete all tables in bangazon.db(CustomerIncidentPortal) then repopulate with PopulateSQL.sql
1. Run all corresponding tests.

### CODE REVIEW

**Review by delaineackerman — COMMENTED** [review]
Add a space before Label 2. Otherwise it works for me!

**Review by JamsDuke — COMMENTED** [review]
Pulled and test, LGTM

**Review by thrashMoneyVillainare — COMMENTED** [review]
💎

**Comment by HubDub** [comment]
The tests all pass and I can create new incidents.

**Review by Jgregnier — APPROVED** [review]
🔑

**Pull request merged**
